stages:
  download_data:
    cmd: python src/data/load_raw_data_from_s3.py configs/data_load.yaml
    deps:
      - configs/data_load.yaml
      - src/data/load_raw_data_from_s3.py
    outs:
      - data/raw/heart_cleveland_upload.csv
#  process data:
#    cmd: mlops_homework_process_dataset
#    deps:
#      - mlops_homework/features/build_features.py
#      - data/raw/heart_cleveland_upload.csv
#    outs:
#      - data/processed/heart_cleveland_upload.csv
#      - models/encoder_baseline.pkl
#  train model:
#    cmd: mlops_homework_train_model
#    deps:
#      - data/processed/heart_cleveland_upload.csv
#      - mlops_homework/models/train_model.py
#      - mlops_homework/models/baseline/train_baseline_model.py
#    outs:
#      - models/baseline.pkl
#    params:
#      - model